layer.conf: Switch GOVERSION to 1.10 to fix build break [YOCIMX-3385]
Error: undefined: DisallowUnknownFields.

The default GOVERSION is 1.9 in sumo,
but DisallowUnknownFields is defined in 1.10.
So switch to 1.10 to fix build break.

Signed-off-by: Yuqing Zhu <carol.zhu@nxp.com>